config/routes.rb
Rails.application.routes.draw do
  get '/fonts/:name.otf', to: 'fonts#show'
  resources :payments, only: [:new, :index, :create]
  resources :categories, except: [:update, :edit]
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_scope :user do
    authenticated :user do
      root "categories#index", as: :authenticated_root
    end
  
    unauthenticated do
      root 'home#index'
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, all, public: true

    return unless user.present? # additional permissions for logged in users (they can read their own post)

    can :manage, all, user:
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :payments, dependent: :destroy

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :categories, dependent: :destroy

  validates :name, presence: true
  validates :amount, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :categories
  has_many :payments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  def current_path
    url_for(request.fullpath)
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/fonts_controller.rb
class FontsController < ApplicationController
  def show
    # Set the name variable to the value of the Proxima font file.
    'Proxima'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[show edit update destroy]
  before_action :category_params, only: %i[destroy]

  # GET /payments or /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1 or /payments/1.json
  def show; end

  # GET /payments/new
  def new
    @payment = Payment.new
    @user_categories = Category.where(user_id: current_user.id)
  end

  # GET /payments/1/edit
  def edit; end

  # POST /payments or /payments.json
  def create
    params = payment_params

    @payment = Payment.new(name: params[:name], amount: params[:amount])
    @payment.user_id = current_user.id
    category_ids = params[:category_ids]
    category_ids.each do |id|
      category = Category.find(id) unless id == ''
      @payment.categories.push(category) unless category.nil?
    end

    respond_to do |format|
      if @payment.save
        format.html { redirect_to categories_url, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy
    @category = category_params

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = Payment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def payment_params
    params.require(:payment).permit(:name, :amount, category_ids: [])
  end

  def category_params
    params.permit(:id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/fonts_helper.rb
module FontsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="flex items-center h-full gap-2">
  <div class="w-14 h-full">
    <img class="w-full h-full" src="<%= category.icon %>">
  </div>
  <p class="font-bold grow">
    <%= category.name %>
  </p>
  <p class="mr-1 text-xs font-bold text-gray-500">
    <%= category.payments.sum(:amount) %> $
  </p>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "h-full flex flex-col justify-between") do |form| %>
    <div>
      <div class="mt-4">
        <%= form.text_field :name, placeholder: "Name", autofocus: true, class: "border border-slate-200 w-full outline-0 px-2 py-1" %>
      </div>

      <div>
        <%= form.text_field :icon, placeholder: "Icon URL", class: "border border-slate-200 w-full outline-0 px-2 py-1" %>
      </div>
    </div>

    <% if category.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

        <ul>
          <% category.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

   <div class="background-green p-3">
      <%= form.submit "Add Category", class: "w-full text-white rounded-md text-center py-2 border-2 font-bold boreder-white" %>
    </div>
  <% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<div class="h-full flex flex-col justify-between">
  <ul id="categories" class="flex flex-col grow p-2 mt-2 gap-2">
    <% @categories.each do |category| %>
      <li class="flex border bg-white rounded-lg overflow-hidden h-14">
        <%= link_to category, class: "grow" do %>
          <%= render category %>
        <% end %>
        <div class="self-end bg-red-700 h-full flex justify-center items-center w-14">
          <%= button_to category, method: :delete do %>
            <i class="fa-solid fa-trash-can text-white text-xl"></i>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>

  <div class="background-green p-3">
    <%= link_to "New category", new_category_path, class: "text-white border-2 border-white w-full block text-center py-2 rounded-sm font-bold" %>
  </div>
</div>

app/views/categories/new.html.erb
<%= render "form", category: @category %>

app/views/categories/show.html.erb
<div class="h-full flex flex-col">
  <div class="flex border bg-white rounded-lg overflow-hidden h-14 mb-5">
    <div class="grow">
      <%= render @category %>
    </div>
  </div>

  <div id="payments">
    <ul class="px-3 gap-2 flex flex-col">
      <% @category.payments.each do |payment| %>
        <li class="flex items-center h-full gap-2 bg-white px-3 rounded overflow-hidden h-12">
            <p class="font-bold grow">
              <%= payment.name %>
            </p>
            <div class="mr-1 text-xs font-bold text-gray-600 flex flex-col text-right">
              <span><%= payment.amount %> $</span>
              <span><%= payment.created_at.to_date %></span>
            </div>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="background-green p-3 mt-auto">
    <%= link_to "New payment", new_payment_path, class: "text-white border-2 border-white w-full block text-center py-2 rounded-sm font-bold" %>
  </div>
</div>

app/views/home/index.html.erb
<div class="flex h-full w-full flex-wrap justify-center p-5">
  <div class="basis-full self-end text-center">
    <h1 class="text-3xl font-bold ff-pacifico">Budget App</h1>
  </div>
  <div class="flex flex-col self-end max-w-xs w-full gap-3 text-center">
    <%= link_to "LOG IN", new_user_session_path, class: 'background-blue w-full rounded-md p-2 font-bold text-white'%>
    <%= link_to "SIGN UP", new_user_registration_path, class: 'w-full font-bold'%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "https://fonts.googleapis.com/css2?family=Pacifico&display=swap", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"/>
    <link rel="stylesheet" href="https://unpkg.com/flowbite@1.4.2/dist/flowbite.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/all.min.js"></script>
  </head>

  <body class="h-screen w-screen bg-gray-200 flex flex-col">
    <% if user_signed_in? %>
      <nav class="border-gray-200 px-2 sm:px-4 py-1 background-blue text-white">
        <div class="container flex flex-wrap justify-between items-center mx-auto">
          <button class="p-2 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-blue-200 dark:text-blue-400 dark:hover:bg-blue-700 dark:focus:ring-blue-600" id="hamburgerMenuBtn">
            <i class="fa-solid fa-bars text-xl text-white"></i>
          </button>
          <span>
            <%= 'Categories' if request.path == "/categories" %>
            <%= 'New ' if request.path == "/categories/new" %>
            <%= 'Category' if request.path.include? "/categories/" %>
            <%= 'New Payment' if request.path.include? "/payments/" %>
          </span>
          <i class="fa-solid fa-magnifying-glass"></i>
          <div class="fixed backdrop-blur transition-all -translate-x-full w-screen h-screen bg-red inset-0" id="mobile-menu-backdrop">
            <div class="w-3/5 fixed md:block h-screen background-blue inset-0 border-r-2 border-slate-400" id="mobile-menu">
              <ul class="flex flex-col font-bold md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium items-center gap-2 py-10 h-full justify-between">
                <li>
                  <%= link_to "Categories", categories_path %>
                </li>
                <li class="bg-red-700 w-full text-center py-3">
                  <%= button_to "Sign out", destroy_user_session_path, :method => :delete, class: 'text-red-50 font-bold'%>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </nav>
    <% end %>

    <%= yield %>

    <script src="https://unpkg.com/flowbite@1.4.2/dist/flowbite.js"></script>
    <script>
      const mobileMenuContainer = document.getElementById("mobile-menu-backdrop")
      const mobileMenu = document.getElementById("mobile-menu")
      document.getElementById("hamburgerMenuBtn").addEventListener("click", () => {
        mobileMenuContainer.classList.remove('-translate-x-full');
      });
      [mobileMenuContainer].forEach((elem) => {
        elem.addEventListener("click", (e) => {
          if(e.target.id === "mobile-menu") return;
          mobileMenuContainer.classList.add('-translate-x-full');
        })
      });
    </script>
  </body>
</html>

app/views/payments/_form.html.erb
<%= form_with(model: payment, class: "h-full flex flex-col") do |form| %>
    <div>
      <%= form.text_field :name, placeholder: "Name", autofocus: true, class: "border border-slate-200 w-full outline-0 px-2 py-1 mt-3" %>
    </div>
  
    <div>
      <%= form.number_field :amount, placeholder: "Amount", class: "border border-slate-200 w-full outline-0 px-2 py-1" %>
    </div>
  
    <div>
      <%= form.select :category_ids, @user_categories.collect {|cat| [cat.name, cat.id]}, { include_blank: false }, required: true, class:"py-2 appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline", multiple: true %>
    </div>
  
    <% if payment.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>
  
        <ul>
          <% payment.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="background-green p-3 mt-auto">
      <%= form.submit "Add Payment", class: "w-full text-white rounded-md text-center py-2 border-2 font-bold boreder-white" %>
    </div>
  <% end %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
  <p>
    <strong>Name:</strong>
    <%= payment.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= payment.amount %>
  </p>

</div>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Show this payment", @payment %> |
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Payments</h1>

<div id="payments">
  <% @payments.each do |payment| %>
    <%= render payment %>
    <p>
      <%= link_to "Show this payment", payment %>
    </p>
  <% end %>
</div>

<%= link_to "New payment", new_payment_path %>

app/views/payments/new.html.erb
<%= render "form", payment: @payment %>

app/views/payments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @payment %>

<div>
  <%= link_to "Edit this payment", edit_payment_path(@payment) %> |
  <%= link_to "Back to payments", payments_path %>

  <%= button_to "Destroy this payment", @payment, method: :delete %>
</div>